# Generated by Django 3.1.4 on 2021-01-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('telephone', models.CharField(max_length=15, verbose_name='telefono/celular')),
                ('mail', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('street', models.CharField(max_length=100, verbose_name='calle')),
                ('number', models.IntegerField(verbose_name='altura')),
                ('floor', models.CharField(max_length=5, verbose_name='piso')),
                ('dept', models.CharField(max_length=5, verbose_name='departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('telephone', models.CharField(max_length=15, verbose_name='telefono/celular')),
                ('mail', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('join_date', models.DateField(verbose_name='fecha de inicio de actividades')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='modelo')),
                ('modality', models.CharField(max_length=50, verbose_name='modalidad de entrega')),
                ('value_prefolding', models.DecimalField(decimal_places=2, help_text='Este es el valor que cobra Gaby por el trabajo por cada millar', max_digits=20, verbose_name='valor de predoblado')),
                ('value_window', models.DecimalField(decimal_places=2, help_text='Este es el valor que cobra Gaby por el trabajo por cada millar', max_digits=20, verbose_name='valor de ventana')),
                ('value_lateral', models.DecimalField(decimal_places=2, help_text='Este es el valor que cobra Gaby por el trabajo por cada millar', max_digits=20, verbose_name='valor de lateral')),
                ('value_bottom', models.DecimalField(decimal_places=2, help_text='Este es el valor que cobra Gaby por el trabajo por cada millar', max_digits=20, verbose_name='valor de fondeo')),
                ('value_millar', models.DecimalField(decimal_places=2, help_text='Este es el valor que cobra Gaby por el trabajo por cada millar', max_digits=20, verbose_name='valor del millar')),
                ('comision_prefolding', models.DecimalField(decimal_places=2, help_text='Este es el valor que paga Gaby a cada pegadora por el trabajo por cada millar', max_digits=20, verbose_name='comision de predoblado')),
                ('comision_window', models.DecimalField(decimal_places=2, help_text='Este es el valor que paga Gaby a cada pegadora por el trabajo por cada millar', max_digits=20, verbose_name='comision de ventana')),
                ('comision_lateral', models.DecimalField(decimal_places=2, help_text='Este es el valor que paga Gaby a cada pegadora por el trabajo por cada millar', max_digits=20, verbose_name='comision de lateral')),
                ('comision_bottom', models.DecimalField(decimal_places=2, help_text='Este es el valor que paga Gaby a cada pegadora por el trabajo por cada millar', max_digits=20, verbose_name='comision de fondeo')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pegado.client', verbose_name='cliente')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegado.material', verbose_name='material')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(verbose_name='fecha de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='monto')),
                ('id_workername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pegado.worker', verbose_name='pegadora')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('prefolding', models.BooleanField(help_text='Indica si se realizo predoblado', verbose_name='predoblado')),
                ('window', models.BooleanField(help_text='Indica si se realizo ventana', verbose_name='ventana')),
                ('lateral', models.BooleanField(help_text='Indica si se realizo lateral', verbose_name='lateral')),
                ('bottom', models.BooleanField(help_text='Indica si se realizo fondeo', verbose_name='fondeo')),
                ('is_complete', models.BooleanField(help_text='Indica si el pedido esta terminado completamente', verbose_name='completo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='monto del trabajo')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='pegado.product', verbose_name='modelo')),
                ('id_workername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='pegado.worker', verbose_name='pegadora')),
            ],
        ),
    ]
