# Generated by Django 3.1.4 on 2021-01-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='net_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='saldo'),
        ),
    ]
