# Generated by Django 3.1.4 on 2021-01-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegado', '0003_auto_20210107_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'material', 'verbose_name_plural': 'materiales'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'trabajo', 'verbose_name_plural': 'trabajos'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'pago', 'verbose_name_plural': 'pagos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'pegadora', 'verbose_name_plural': 'pegadoras'},
        ),
    ]
